version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: msmysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ENEM_2020
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  etl:
    build: .
    container_name: etl
    volumes:
      - ./main.py:/app/main.py
      - ./staging/DADOS/MICRODADOS_ENEM_2020.csv:/app/MICRODADOS_ENEM_2020.csv
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ENEM_2020
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    command: ["sh", "-c", "venv/bin/python etl.py"]

volumes:
  db_data:
